classes = ['cardboard', 'glass', 'metal','paper', 'plastic', 'trash']
AN_table  = { "paper" : [ "plastic", "cardboard", "metal", "trash"], "plastic" : ["paper", "cardboard", "metal", "trash"], "cardboard" : ["paper", "plastic", "metal", "trash"], "metal" : ["paper", "plastic", "cardboard", "trash"], "glass" : ["trash"], "trash" : []}
nb_classes = 6
class_to_index_dictionnary = {'cardboard':0, 'glass':1, 'metal':2,'paper':3, 'plastic':4, 'trash':5}
BASE_DIR = '../data/dataset-resized/'
WIDTH = 224
HEIGHT = 224
BATCH_SIZE = 64
epoch = 40
filepath = "bestmodel.h5"
typesFr = ['recyclable', 'verre', 'non recyclable']
modeltype = "resnet50"
optimizer_type = "rmsprop"
classes_to_trash = {'cardboard':0, 'glass':1, 'metal':0,'paper':0, 'plastic':0, 'trash':2}